server:
  port: 8900
spring:
  application:
    name: soa-mix-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/gbck-test?characterEncoding=utf-8
    dbcp2:
      initial-size: 5
      max-total: 10
      min-idle: 1
      time-between-eviction-runs-millis: 360000
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
      validation-query: SELECT 1

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql

biz:
  soa:
    idx: 1
  zookeeper:
    url: zookeeper://127.0.0.1:2181
    soaIdx:
      path: /biz/gbck/boot/soaIdx
    #redis:
    #  path: /biz/gbck/boot/redis
  redis:
    maxTotal: 120
    maxIdle: 10
    timeBetweenEvictionRunsMillis: 30000
    minEvictableIdleTimeMillis: 30000
    testOnBorrow: true
    host: 127.0.0.1
    port: 6379
    name:
    password:
  amqp:
    host: 10.4.100.196
    username: guest
    password: guest
    port: 5672
    maxRetry: 3
    retryElapse: 1000
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7777/eureka/
  instance:
    prefer-ip-address: true
  server:
    eviction-interval-timer-in-ms: 1000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
ribbon:
  ReadTimeout: 30000
feign:
  hystrix:
    enabled: true

