spring:
  application:
    name: depotnextdoor-rest
server:
  port: 8999
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7777/eureka/, http://localhost:8888/eureka/, http://localhost:9999/eureka/
security:
  basic:
    enabled: false
    authorize-mode: none