spring:
  application:
    name: depotnextdoor-rest
server:
  port: 8999
eureka:
  client:
    service-url:
      defaultZone: http://10.4.100.194:7777/eureka/,http://10.4.100.195:7777/eureka/,http://10.4.100.196:7777/eureka/
security:
  basic:
    enabled: false
    authorize-mode: none
