spring:
  application:
    name: soa-order
  profiles:
    active: internal

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://127.0.0.1:3306/biz
    dbcp2:
      initial-size: 5
      max-total: 10
      min-idle: 1
      time-between-eviction-runs-millis: 360000
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
      validation-query: SELECT 1

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
  session:
    redis:
      flush-mode: immediate

biz:
  soa:
    idx: 1
  zookeeper:
    url: zookeeper://127.0.0.1:2181
    soaIdx:
      path: /biz/gbck/boot/soaIdx
    #redis:
    #  path: /biz/gbck/boot/redis
  redis:
    maxTotal: 120
    maxIdle: 10
    timeBetweenEvictionRunsMillis: 30000
    minEvictableIdleTimeMillis: 30000
    testOnBorrow: true
    host: 127.0.0.1
    port: 6379
    name:
    password:
  amqp:
    username: guest
    password: guest
    host: 127.0.0.1
    port: 5672
    maxRetry: 3
    retryElapse: 1000

server:
  session:
    timeout: 1200
security:
  basic:
    enabled: false
management:
  security:
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:5555/eureka

payment:
  alipay:
    notify-url: http://external.com/alipay/notify.do
  wechat:
    appid.default: wxe458de408eef40eb
    mch_id.wxe458de408eef40eb: 1340664401
    key.wxe458de408eef40eb: 9d49f4f815890c8ef39935a271c38bd7
    LOAD_IDENTIFICATION.wxe458de408eef40eb: /wxe458de408eef40eb_apiclient_cert.p12
    notify-url: http://external.com/wechatPay/notify.do