spring:
  profiles:
    active: dev
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-name: depotnextdoor
      cluster-nodes: 127.0.0.1:9300
server:
  port: 9800

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7777/eureka/
security:
  basic:
    enabled: false
    authorize-mode: none